version: "3"

services:
  server:
    container_name: "jwt_server"
    build:
      context: ./server
      dockerfile: Dockerfile
    working_dir: /var/www/server
    volumes:
      - "./server:/var/www/server:rw"
      - "/var/www/server/node_modules"
    expose:
      - 5000
    env_file:
      - ./server/.env
    ports:
      - 5000:5000
    depends_on:
      - mongo
    restart: always
    networks:
      - node-jwt-network

  mongo:
    container_name: "jwt_mongo_db"
    image: mongo:3.6.19-xenial
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=app_user
      - MONGO_INITDB_ROOT_PASSWORD=app_password
      - MONGO_INITDB_DATABASE=admin
    networks:
      - node-jwt-network

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    environment:
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_ADMINUSERNAME=app_user
      - ME_CONFIG_MONGODB_ADMINPASSWORD=app_password
      - ME_CONFIG_BASICAUTH_USERNAME=app_user
      - ME_CONFIG_BASICAUTH_PASSWORD=app_password
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
    ports:
      - "0.0.0.0:8081:8081"
    networks:
      - node-jwt-network
    depends_on:
      - mongo

networks:
  node-jwt-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local
